Table prices {
    id integer [primary key]
    amount decimal(10, 2)
    rate numeric(18, 4)
    compact decimal(3,5)
    large_precision decimal(131072, 2)
    label varchar(255)
    code char(10)
    score float(24)
}
